config/routes.rb
Rails.application.routes.draw do
  resources :document_boxes
  resources :minutes_boxes, only: :create
  resources :other_boxes, only: :create
  root to: "document_boxes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document_box.rb
class DocumentBox < ApplicationRecord
  mount_uploader :document, DocumentUploader
end

app/models/minutes_box.rb
class MinutesBox < ApplicationRecord
  mount_uploader :meeting, MeetingUploader
end

app/models/other_box.rb
class OtherBox < ApplicationRecord
  mount_uploader :other, OtherUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/document_boxes_controller.rb
class DocumentBoxesController < ApplicationController
  before_action :set_document_box, only: [:show, :edit, :update, :destroy]

  # GET /document_boxes
  # GET /document_boxes.json
  def index
    @document_boxes = DocumentBox.all
  end

  # GET /document_boxes/1
  # GET /document_boxes/1.json
  def show
  end

  # GET /document_boxes/new
  def new
    @document_box = DocumentBox.new
  end

  # GET /document_boxes/1/edit
  def edit
    if @document_box.name.nil?
      @file_name = @document_box.document.file.basename
    else
      @file_name = @document_box.name
    end
  end

  # POST /document_boxes
  # POST /document_boxes.json
  def create
    @document_box = DocumentBox.create({'document': params.require(:file)})
    # @document_box = DocumentBox.new(document_box_params)

    # respond_to do |format|
    #   if @document_box.save
    #     format.html { redirect_to @document_box, notice: 'Document box was successfully created.' }
    #     format.json { render :show, status: :created, location: @document_box }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @document_box.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /document_boxes/1
  # PATCH/PUT /document_boxes/1.json
  def update
    respond_to do |format|
      if @document_box.update(document_box_params)
        format.html { redirect_to @document_box, notice: 'Document box was successfully updated.' }
        format.json { render :show, status: :ok, location: @document_box }
      else
        format.html { render :edit }
        format.json { render json: @document_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_boxes/1
  # DELETE /document_boxes/1.json
  def destroy
    @document_box.destroy
    respond_to do |format|
      format.html { redirect_to document_boxes_url, notice: 'Document box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_box
      @document_box = DocumentBox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_box_params
      params.require(:document_box).permit(:document, :name)
    end
end

app/controllers/minutes_boxes_controller.rb
class MinutesBoxesController < ApplicationController
  def create
    @minutes_box = MinutesBox.create({'meeting': params.require(:file)})
  end
end

app/controllers/other_boxes_controller.rb
class OtherBoxesController < ApplicationController
  def create
    @other_box = OtherBox.create({'other': params.require(:file)})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_boxes_helper.rb
module DocumentBoxesHelper
end

app/helpers/minutes_boxes_helper.rb
module MinutesBoxesHelper
end

app/helpers/other_boxes_helper.rb
module OtherBoxesHelper
end

app/views/document_boxes/_form.html.haml
= form_tag(document_boxes_path, class: 'dropzone', id: 'upload-dropzone') do
  .fallback
    = file_field_tag('attach[file]')
%br/
= form_tag(minutes_boxes_path, class: 'dropzone', id: 'upload-dropzone') do
  .fallback
    = file_field_tag('attach[file]')
%br/
= form_tag(other_boxes_path, class: 'dropzone', id: 'upload-dropzone') do
  .fallback
    = file_field_tag('attach[file]')

app/views/document_boxes/edit.html.haml
%h1 Editing Document Box

= form_with(model: @document_box, local: true) do |f|
  = f.text_field :name, value: @file_name
  = f.submit

= link_to 'Show', @document_box
|
= link_to 'Back', document_boxes_path

app/views/document_boxes/index.html.haml
%p#notice= notice
%h1 Document Boxes
%table
  %thead
    %tr
      %th Document
      %th{:colspan => "3"}
  %tbody
    - @document_boxes.each do |document_box|
      %tr
        - if document_box.name.nil?
          %td= document_box.document.file.basename
        - else
          %td= document_box.name
        %td= image_tag(document_box.document_url, width: 100) if document_box.document?
        %td= link_to '書類へのリンク', document_box.document_url
        %td= link_to 'Show', document_box
        %td= link_to 'Edit', edit_document_box_path(document_box)
        %td= link_to 'Destroy', document_box, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Document Box', new_document_box_path

app/views/document_boxes/new.html.haml
%h1 New Document Box
= render 'form', document_box: @document_box
= link_to 'Back', document_boxes_path

app/views/document_boxes/show.html.haml
%p#notice= notice
%p
  %strong Document:
  = @document_box.document
= link_to 'Edit', edit_document_box_path(@document_box)
|
= link_to 'Back', document_boxes_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SampleDropzone
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield